// frontend/app/components/Common/Skeleton.tsx
export default function Skeleton() {
  return (
    <div className="flex w-96 flex-col gap-4">
      <div className="skeleton h-32 w-full"></div>
      <div className="skeleton h-4 w-48"></div>
      <div className="skeleton h-4 w-full"></div>
      <div className="skeleton h-4 w-full"></div>
    </div>
  );
}

// frontend/src/lib/recommendation/Skeleton.svelte
<div class="flex w-96 flex-col gap-4">
	<div class="flex items-center gap-4">
		<div class="skeleton h-16 w-16 shrink-0 rounded-full"></div>
		<div class="flex flex-col gap-4">
			<div class="skeleton h-4 w-20"></div>
			<div class="skeleton h-4 w-28"></div>
		</div>
	</div>
	<div class="skeleton h-32 w-full"></div>
</div>
