// frontend/src/lib/recommendation/RecommendationCard.svelte
<script lang="ts">
	let { program_title, university, i } = $props();
	let university_abbreviation: string = $derived.by(() => {
		let processed = university.toLowerCase();
		let lastElement = processed.split(' ').pop() || '';
		return `${lastElement.replace(/[()]/g, '')}`;
	});
	let image_src: string = $derived(`${university_abbreviation}.webp`);
	let card_url: string = $derived(`https://www.${university_abbreviation}.edu.sg`);
	let ranking: string = $derived.by(() => {
		return i === 0 ? '🥇' : i === 1 ? '🥈' : i === 2 ? '🥉' : `${i + 1}.`;
	});
</script>

<a href={card_url} target="_blank" rel="noopener noreferrer">
	<div
		class="flex h-36 w-full max-w-xl space-x-2 overflow-hidden rounded-xl bg-zinc-800 shadow-md transition-all duration-300 hover:scale-105"
	>
		<div class="h-36 w-36 flex-shrink-0">
			<img src={image_src} alt={university} class="h-full w-full object-cover" />
		</div>
		<div class="flex flex-1 flex-col justify-center p-3">
			<h3 class="text-md line-clamp-3 font-semibold leading-tight sm:text-lg">
				{ranking}
				{program_title}
			</h3>
			<p class="mt-1 text-base">
				{university}
			</p>
		</div>
	</div>
</a>

// frontend/app/components/Recommendation/RecommendationCard.tsx
import Link from "next/link";
import UniversityBadge from "../Common/UniversityBadge";
import { Recommendation } from "@/app/api/useRecommend";

const RecommendationCard = ({ program_title, university }: Recommendation) => {
  const link = `https://${university
    .toLowerCase()
    .split(" ")
    .at(-1)
    ?.replace(/[()']/g, "")}.edu.sg/`;
  return (
    <Link href={link}>
      <div className="group m-4 max-w-3xl rounded-xl border bg-base-100 p-4 shadow transition-all duration-300 hover:shadow-md">
        <div className="flex items-center space-x-4">
          <div className="flex-shrink-0">
            <UniversityBadge university={university} />
          </div>

          <div className="flex flex-col">
            <span className="text-base font-medium text-base-content">
              {program_title}
            </span>
            <span className="text-sm text-base-content/60">{university}</span>
          </div>
        </div>
      </div>
    </Link>
  );
};

export default RecommendationCard;
